[2023-06-04T11:26:35.430+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: most_popular_movies.scrape_movies manual__2023-06-04T11:26:34.095131+00:00 [queued]>
[2023-06-04T11:26:35.437+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: most_popular_movies.scrape_movies manual__2023-06-04T11:26:34.095131+00:00 [queued]>
[2023-06-04T11:26:35.437+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-04T11:26:35.448+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): scrape_movies> on 2023-06-04 11:26:34.095131+00:00
[2023-06-04T11:26:35.453+0000] {standard_task_runner.py:57} INFO - Started process 3732 to run task
[2023-06-04T11:26:35.456+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'most_popular_movies', 'scrape_movies', 'manual__2023-06-04T11:26:34.095131+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/most_popular_movies.py', '--cfg-path', '/tmp/tmpllwbejbo']
[2023-06-04T11:26:35.456+0000] {standard_task_runner.py:85} INFO - Job 102: Subtask scrape_movies
[2023-06-04T11:26:35.491+0000] {task_command.py:410} INFO - Running <TaskInstance: most_popular_movies.scrape_movies manual__2023-06-04T11:26:34.095131+00:00 [running]> on host 7633a4fabdb3
[2023-06-04T11:26:35.554+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='most_popular_movies' AIRFLOW_CTX_TASK_ID='scrape_movies' AIRFLOW_CTX_EXECUTION_DATE='2023-06-04T11:26:34.095131+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-04T11:26:34.095131+00:00'
[2023-06-04T11:26:36.608+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/most_popular_movies.py", line 24, in scrape_movies
    movie_df = _scrape_movies(soup)
  File "/opt/airflow/dags/helper/scrape_imdb_charts.py", line 78, in _scrape_movies
    movie_ratings.append(float(rating.find("strong").text))
AttributeError: 'NoneType' object has no attribute 'text'
[2023-06-04T11:26:36.614+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=most_popular_movies, task_id=scrape_movies, execution_date=20230604T112634, start_date=20230604T112635, end_date=20230604T112636
[2023-06-04T11:26:36.623+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 102 for task scrape_movies ('NoneType' object has no attribute 'text'; 3732)
[2023-06-04T11:26:36.630+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-04T11:26:36.648+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
